apiVersion: apps/v1
kind: Deployment
metadata:
  name:  test-dep
  labels:
    app:  test-dep
spec:
  selector:
    matchLabels:
      app: test-dep
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  test-dep
    spec:
      containers:
      - name:  test-dep
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
        ports:
        - containerPort:  80
          name:  test-dep
      restartPolicy: Always
---

